include: package:lint/analysis_options_package.yaml

analyzer:
  # exclude:
  #   - example/**
  #   - example/tale_drawer_example/**

  errors:
    prefer_const_constructors: ignore
    sort_pub_dependencies: ignore
    constant_identifier_names: ignore
    avoid_positional_boolean_parameters: ignore
    prefer_initializing_formals: ignore
    use_setters_to_change_properties: ignore
    sort_unnamed_constructors_first: ignore